#!/bin/bash

IMAGE=gregorwebmaster/dockertools:builder
BUILD_CONTAINER=dockertools-builder

run_interactive () {
    docker run -v $PWD:/workspace -it --rm --name $BUILD_CONTAINER $IMAGE  bash
}

npm_install () {
    docker run -v $PWD:/workspace --rm --name $BUILD_CONTAINER $IMAGE  npm install --dd
}

assets_prod () {
    docker run -v $PWD:/workspace --rm --name $BUILD_CONTAINER $IMAGE  npm run production
}

assets_dev () {
    docker run -v $PWD:/workspace --rm --name $BUILD_CONTAINER $IMAGE  npm run dev
}

assets_watch () {
    docker run -v $PWD:/workspace --rm --name $BUILD_CONTAINER $IMAGE  npm run watch
}

$*