version: '3'
services:
  web:
    container_name: web-serv
    image: nginx:1.15-alpine
    volumes: 
      - ./dist:/var/www
      - ./config/dev-serv/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    links:
      - php7
    
  php7:
    container_name: php-debug
    build: ./docker/php_debug
    image: php_debug:0.1
    volumes: 
      - ./dist:/var/www