version: '3'
services:
  web:
    container_name: web-serv
    image: nginx:1.15-alpine
    volumes: 
      - ./dist:/var/www
      - ./config/dev-serv/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    links:
      - php7
    networks:
      dockertools:
        ipv4_address: 172.11.2.2
    
  php7:
    image: gregorwebmaster/dockertools:xdebug
    volumes: 
      - ./dist:/var/www
    networks:
      dockertools:
        ipv4_address: 172.11.2.3
    environment:
      XDEBUG_CONFIG: idekey=VSCODE
      
networks:
  dockertools:
    driver: bridge
    ipam:
     config:
        - subnet: 172.11.2.0/24